version: '3.7'

services:
  web:
    build:
        context: ./app
        dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/opt/app/
    ports:
      - 4000:8000
    env_file:
      - ./env/django.env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/postgres/data/
    env_file: 
        - ./env/postgresql.env

volumes:
      postgres_data:
        driver: local